const questions=[
 {key:'occasion',title:'مناسبت',kicker:'شروع کنیم',text:'این هدیه قرار است چه لحظه‌ای را خاص کند؟',hint:'اگر مناسبت دقیقی نداری، «بی‌مناسبت» را بزن.',options:[['birthday','تولد','یک جشن شخصی و شاد','🎂'],['love','سالگرد یا عاشقانه','برای یک خاطره‌ی دونفره','💞'],['thanks','تشکر و موفقیت','قدردانی یا تبریک یک دستاورد','🌟'],['now','بی‌مناسبت','فقط برای خوشحال‌کردنش','🎈']]},
 {key:'relation',title:'رابطه',kicker:'برای چه کسی؟',text:'رابطه‌ات با کسی که هدیه می‌گیرد چیست؟',hint:'میزان صمیمیت، پیشنهادها را بهتر می‌کند.',options:[['partner','همسر یا پارتنر','صمیمی و احساسی','❤️'],['friend','دوست','خودمانی و خوش‌حال‌کننده','🫶'],['family','عضو خانواده','گرم و با محبت','🏡'],['work','همکار یا مدیر','شیک و حساب‌شده','💼']]},
 {key:'age',title:'سن',kicker:'کمی دقیق‌تر',text:'در چه بازه‌ی سنی است؟',hint:'تقریبی بودن کاملاً کافی است.',options:[['teen','زیر ۲۰ سال','نوجوان و پرانرژی','⚡'],['young','۲۰ تا ۳۵ سال','جوان و تجربه‌دوست','🌱'],['adult','۳۶ تا ۵۰ سال','با سلیقه و انتخاب‌گر','✨'],['senior','بیشتر از ۵۰ سال','ماندگار و باوقار','🌿']]},
 {key:'interest',title:'علاقه',kicker:'دنیای موردعلاقه‌اش',text:'بیشتر وقت آزادش را با کدام می‌گذراند؟',hint:'نزدیک‌ترین گزینه را انتخاب کن.',options:[['culture','هنر، کتاب و موسیقی','قصه، خلاقیت و یادگیری','🎨'],['tech','فناوری و بازی','گجت و سرگرمی دیجیتال','🎮'],['home','خانه، خوراکی و آرامش','فضای دلنشین و مزه‌های تازه','☕'],['outdoor','سفر، ورزش و تجربه','کشف‌کردن و خاطره ساختن','🧭']]},
 {key:'type',title:'نوع هدیه',kicker:'چه چیزی بیشتر خوشحالش می‌کند؟',text:'دوست داری هدیه‌ات چه حال‌وهوایی داشته باشد؟',hint:'این سؤال کمک می‌کند پیشنهادها واقعاً متنوع بمانند.',options:[['personalized','شخصی‌سازی‌شده','فقط برای او ساخته شده باشد','🪄'],['object','یک وسیله‌ی باکیفیت','بازش کند و نگهش دارد','🎁'],['experience','یک تجربه‌ی تازه','خاطره به‌جای وسیله','🎟️'],['digital','دیجیتال یا فوری','بدون نگرانی ارسال','💳']]},
 {key:'personality',title:'شخصیت',kicker:'کدام توصیف نزدیک‌تر است؟',text:'سبک انتخاب‌هایش چطور است؟',hint:'اولین چیزی که به ذهنت رسید معمولاً درست است.',options:[['practical','کاربردی و منطقی','چیزی که زیاد استفاده شود','🧩'],['emotional','احساسی و خاطره‌باز','معنا مهم‌تر از قیمت است','💌'],['minimal','مینیمال و سخت‌پسند','ساده، اصیل و باکیفیت','◻️'],['adventurous','کنجکاو و ماجراجو','چیز تازه را دوست دارد','🚀']]},
 {key:'delivery',title:'زمان',kicker:'چقدر فرصت داری؟',text:'هدیه را چه زمانی باید تحویل بدهی؟',hint:'بعضی هدیه‌های سفارشی به زمان بیشتری نیاز دارند.',options:[['urgent','امروز یا فردا','فوری یا دیجیتال','⚡'],['week','تا یک هفته','زمان کافی برای ارسال','📦'],['later','بیشتر از یک هفته','سفارشی‌سازی هم ممکن است','🗓️'],['flexible','زمان مهم نیست','فقط بهترین گزینه را می‌خواهم','✨']]},
 {key:'budget',title:'بودجه',kicker:'آخرین سؤال',text:'حدود بودجه‌ات چقدر است؟',hint:'قیمت و موجودی نهایی را در فروشگاه بررسی کن.',options:[['low','تا ۷۰۰ هزار تومان','کوچک اما دوست‌داشتنی','💛'],['mid','۷۰۰ هزار تا ۲ میلیون','دستت برای انتخاب باز است','💚'],['high','۲ تا ۵ میلیون','یک هدیه‌ی چشم‌گیر','💜'],['premium','بیشتر از ۵ میلیون','خاص و ماندگار','🧡']]}
];

const gifts=[
 {name:'تابلوی صدادار با QR خاطره',emoji:'🎵',desc:'عکس، آهنگ یا صدای شما را در یک قاب شخصی نگه می‌دارد؛ هدیه‌ای کاملاً داستان‌دار.',provider:'صدانما',url:'https://sedanama.com/',tags:['culture','emotional','personalized'],types:['personalized'],budgets:['mid','high'],relations:['partner','friend','family'],occasions:['birthday','love','thanks'],time:['week','later','flexible']},
 {name:'تابلوی آسمان شب یک تاریخ خاص',emoji:'🌌',desc:'نقشه‌ی آسمان شب تولد، آشنایی یا یک تاریخ مشترک؛ شخصی و ماندگار.',provider:'صدانما',url:'https://sedanama.com/',tags:['culture','emotional','minimal'],types:['personalized'],budgets:['mid','high'],relations:['partner','friend','family'],occasions:['birthday','love'],time:['week','later','flexible']},
 {name:'ورکشاپ سفالگری دونفره',emoji:'🏺',desc:'چند ساعت ساختن، خندیدن و بردن یک یادگاری دست‌ساز به خانه.',provider:'چار سرامیک',url:'https://chaarceramic.ir/experiential-gift-tehran/',tags:['outdoor','culture','adventurous','emotional'],types:['experience'],budgets:['mid','high'],relations:['partner','friend','family'],occasions:['birthday','love','now'],time:['week','later','flexible']},
 {name:'کارت هدیه‌ی یک تجربه',emoji:'🎟️',desc:'به‌جای حدس‌زدن یک وسیله، انتخاب تجربه را به خودش بسپار؛ از تفریح تا یادگیری.',provider:'قاصتک',url:'https://ghasetak.ir/',tags:['outdoor','adventurous','practical'],types:['experience','digital'],budgets:['mid','high','premium'],relations:['partner','friend','family','work'],occasions:['birthday','thanks','now'],time:['urgent','week','later','flexible']},
 {name:'اثر صنایع‌دستی معاصر ایرانی',emoji:'🪬',desc:'یک شیء اصیل از سفال، مس، چوب یا دست‌بافته که شبیه هدیه‌های تکراری نیست.',provider:'فروشگاه دریک',url:'https://drikshop.ir/',tags:['culture','home','minimal'],types:['object'],budgets:['mid','high','premium'],relations:['partner','friend','family','work'],occasions:['birthday','thanks','now'],time:['week','later','flexible']},
 {name:'فیروزه‌کوبی فاخر ایرانی',emoji:'💎',desc:'هدیه‌ای رسمی، هنری و ماندگار برای مناسبت مهم یا قدردانی ویژه.',provider:'آقاجانی',url:'https://aghajani.net/',tags:['culture','home','minimal'],types:['object'],budgets:['high','premium'],relations:['family','work','partner'],occasions:['thanks','birthday','love'],time:['week','later','flexible']},
 {name:'شمع دست‌ساز با رایحه‌ی اختصاصی',emoji:'🕯️',desc:'یک هدیه‌ی گرم و خوش‌بو از سازنده‌های مستقل، مناسب لحظه‌های آرام.',provider:'باسلام',url:'https://basalam.com/cat/home/%D8%B4%D9%85%D8%B9-%D8%AF%D8%B3%D8%AA-%D8%B3%D8%A7%D8%B2',tags:['home','emotional','minimal'],types:['object'],budgets:['low','mid'],relations:['partner','friend','family','work'],occasions:['birthday','love','thanks','now'],time:['week','later','flexible']},
 {name:'گیاه خاص با گلدان دست‌ساز',emoji:'🪴',desc:'ترکیب یک گیاه ماندگار با گلدانی که خودش بخشی از هدیه است.',provider:'دیجی‌کالا',query:'گیاه آپارتمانی گلدان دست ساز',tags:['home','emotional','minimal'],types:['object'],budgets:['low','mid'],relations:['partner','friend','family','work'],occasions:['birthday','thanks','now'],time:['week','later','flexible']},
 {name:'پک قهوه‌ تخصصی و ابزار دم‌آوری',emoji:'☕',desc:'چند دانه‌ی تازه‌برشت همراه یک ابزار ساده برای کسی که قهوه را جدی می‌گیرد.',provider:'دیجی‌کالا',query:'پک هدیه قهوه تخصصی ابزار دم آوری',tags:['home','practical','adventurous'],types:['object'],budgets:['low','mid','high'],relations:['partner','friend','family','work'],occasions:['birthday','thanks','now'],time:['week','later','flexible']},
 {name:'بازی رومیزی قصه‌ساز',emoji:'🎲',desc:'هدیه‌ای که همان شب تبدیل به دورهمی، گفتگو و خنده می‌شود.',provider:'دیجی‌کالا',query:'بازی فکری رومیزی بزرگسال',tags:['tech','outdoor','adventurous'],types:['object','experience'],budgets:['low','mid'],relations:['partner','friend','family'],occasions:['birthday','now'],time:['week','later','flexible']},
 {name:'دوربین چاپ سریع',emoji:'📸',desc:'برای ثبت لحظه و تحویل‌گرفتن خاطره در همان چند ثانیه؛ جذاب و مشارکتی.',provider:'دیجی‌کالا',query:'دوربین چاپ سریع',tags:['tech','culture','emotional','adventurous'],types:['object','experience'],budgets:['high','premium'],relations:['partner','friend','family'],occasions:['birthday','love','now'],time:['week','later','flexible']},
 {name:'مینی پروژکتور برای شب فیلم',emoji:'📽️',desc:'یک سینمای کوچک برای اتاق، سفر یا شب‌های دونفره.',provider:'دیجی‌کالا',query:'مینی پروژکتور قابل حمل',tags:['tech','home','practical'],types:['object'],budgets:['high','premium'],relations:['partner','friend','family'],occasions:['birthday','love','now'],time:['week','later','flexible']},
 {name:'صفحه‌کلید مکانیکی شخصی‌سازی‌شده',emoji:'⌨️',desc:'برای گیمر، برنامه‌نویس یا کسی که میز کارش را با وسواس می‌چیند.',provider:'دیجی‌کالا',query:'کیبورد مکانیکال',tags:['tech','practical','minimal'],types:['object'],budgets:['mid','high','premium'],relations:['partner','friend','family','work'],occasions:['birthday','thanks','now'],time:['week','later','flexible']},
 {name:'هدفون حذف نویز',emoji:'🎧',desc:'فضای شخصی برای موسیقی، تمرکز و سفر؛ هدیه‌ای که هر روز استفاده می‌شود.',provider:'دیجی‌کالا',query:'هدفون نویز کنسلینگ',tags:['tech','culture','practical','minimal'],types:['object'],budgets:['high','premium'],relations:['partner','friend','family','work'],occasions:['birthday','thanks','now'],time:['week','later','flexible']},
 {name:'کتاب نفیس با یادداشت دست‌نویس',emoji:'📚',desc:'کتابی متناسب با سلیقه‌اش انتخاب کن و صفحه‌ی اول را با چند خط شخصی کامل کن.',provider:'طاقچه؛ راهنمای انتخاب',url:'https://taaghche.com/blog/1398/08/27/%D8%A8%D9%87%D8%AA%D8%B1%DB%8C%D9%86-%DA%A9%D8%AA%D8%A7%D8%A8-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%87%D8%AF%DB%8C%D9%87-%D8%A8%D9%87-%D8%B9%D8%B4%D9%82/',tags:['culture','emotional','minimal'],types:['object','personalized'],budgets:['low','mid'],relations:['partner','friend','family','work'],occasions:['birthday','love','thanks','now'],time:['urgent','week','later','flexible']},
 {name:'گیفت‌کارت موسیقی، بازی یا اپ',emoji:'💳',desc:'انتخاب فوری برای کسی که دقیقاً می‌داند در دنیای دیجیتال چه می‌خواهد.',provider:'ایرانیکارت',url:'https://www.iranicard.ir/card/giftcard/application-giftcard/',tags:['tech','practical'],types:['digital'],budgets:['low','mid','high'],relations:['partner','friend','family','work'],occasions:['birthday','thanks','now'],time:['urgent','week','later','flexible']},
 {name:'کارت هدیه‌ی سرمایه‌گذاری',emoji:'📈',desc:'هدیه‌ای متفاوت و آینده‌نگر برای کسی که انتخاب کاربردی و مالی را می‌پسندد.',provider:'هدهد فارابی',url:'https://hodhod.irfarabi.com/',tags:['practical','minimal'],types:['digital'],budgets:['mid','high','premium'],relations:['family','work','friend'],occasions:['birthday','thanks'],time:['urgent','week','later','flexible']},
 {name:'کارت بانکی با طرح اختصاصی',emoji:'💳',desc:'هدیه‌ای منعطف با ظاهر شخصی‌سازی‌شده؛ مناسب وقتی انتخاب نهایی را به خودش می‌سپاری.',provider:'دیسماکارت',url:'https://dismacard.com/',tags:['practical','personalized','minimal'],types:['personalized','digital'],budgets:['mid','high','premium'],relations:['partner','friend','family','work'],occasions:['birthday','thanks','love'],time:['week','later','flexible']},
 {name:'پیج هدیه‌های صوتی و تصویری سفارشی',emoji:'📱',desc:'نمونه‌کارها را در اینستاگرام ببین و مستقیم برای ساخت یک هدیه‌ی خاطره‌محور سفارش بده.',provider:'اینستاگرام صدانما',url:'https://instagram.com/sedanama',tags:['culture','emotional','personalized'],types:['personalized'],budgets:['mid','high'],relations:['partner','friend','family'],occasions:['birthday','love','thanks'],time:['week','later','flexible']},
 {name:'پک سفر یک‌روزه و پیک‌نیک',emoji:'🎒',desc:'فلاسک، زیرانداز سبک و یک برنامه‌ی کوچک برای فرار از روزمرگی.',provider:'دیجی‌کالا',query:'پک پیک نیک و سفر',tags:['outdoor','adventurous','practical'],types:['object','experience'],budgets:['mid','high'],relations:['partner','friend','family'],occasions:['birthday','love','now'],time:['week','later','flexible']}
];

let step=0,answers={},currentPicks=[];
const readLocal=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let favoriteNames=readLocal('kadopych:favorites',[]);
let reminders=readLocal('kadopych:reminders',[]);
const $=id=>document.getElementById(id);
function show(section){['intro','quiz','results'].forEach(id=>$(id).classList.toggle('hidden',id!==section));window.scrollTo({top:0,behavior:'smooth'})}
function renderQuestion(){const q=questions[step];$('stepLabel').textContent=`سؤال ${step+1} از ${questions.length}`;$('stepTitle').textContent=q.title;$('progressBar').style.width=`${(step+1)/questions.length*100}%`;$('questionKicker').textContent=q.kicker;$('questionText').textContent=q.text;$('questionHint').textContent=q.hint;$('backBtn').style.visibility=step?'visible':'hidden';$('options').innerHTML='';q.options.forEach(([value,label,sub,icon])=>{const b=document.createElement('button');b.className='option';b.type='button';b.innerHTML=`<span class="option-icon" aria-hidden="true">${icon}</span><span><strong>${label}</strong><small>${sub}</small></span>`;b.onclick=()=>choose(q.key,value,label);$('options').appendChild(b)})}
function choose(key,value,label){answers[key]={value,label};if(step<questions.length-1){step++;renderQuestion()}else renderResults()}
function scoreGift(g){let s=0;if(g.tags.includes(answers.interest.value))s+=7;if(g.tags.includes(answers.personality.value))s+=5;if(g.types.includes(answers.type.value))s+=7;if(g.budgets.includes(answers.budget.value))s+=6;else s-=4;if(g.relations.includes(answers.relation.value))s+=4;if(g.occasions.includes(answers.occasion.value))s+=3;if(g.time.includes(answers.delivery.value))s+=4;else s-=5;return s+Math.random()*.1}
function buyUrl(g){return g.url||`https://www.digikala.com/search/?q=${encodeURIComponent(g.query)}`}
function renderResults(){currentPicks=[...gifts].sort((a,b)=>scoreGift(b)-scoreGift(a)).slice(0,12);$('resultSummary').textContent=`برای ${answers.relation.label} که به «${answers.interest.label}» علاقه دارد، این گزینه‌ها با بودجه‌ی ${answers.budget.label} و زمان ${answers.delivery.label} هماهنگ‌ترند.`;$('giftGrid').innerHTML=currentPicks.map((g,i)=>`<article class="gift-card"><span class="rank">${i===0?'بهترین تطابق':`پیشنهاد ${i+1}`}</span><div class="gift-visual" aria-hidden="true">${g.emoji}</div><h3>${g.name}</h3><p>${g.desc}</p><div class="source">${g.provider}</div><div class="gift-tags"><span>${answers.type.label}</span><span>${answers.budget.label}</span></div><div class="card-tools"><button class="card-tool ${favoriteNames.includes(g.name)?'saved':''}" data-favorite="${g.name}">${favoriteNames.includes(g.name)?'♥ ذخیره شد':'♡ ذخیره'}</button><button class="card-tool" data-share="${g.name}">اشتراک</button></div><a class="buy-link" href="${buyUrl(g)}" target="_blank" rel="noopener noreferrer"><span>دیدن و بررسی خرید</span><span aria-hidden="true">↗</span></a></article>`).join('');$('giftGrid').querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.favorite));$('giftGrid').querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>shareGift(b.dataset.share));show('results')}
function restart(){step=0;answers={};renderQuestion();show('quiz')}
function saveFavorites(){localStorage.setItem('kadopych:favorites',JSON.stringify(favoriteNames));$('favoriteCount').textContent=String(favoriteNames.length).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);renderFavorites()}
function toggleFavorite(name){favoriteNames=favoriteNames.includes(name)?favoriteNames.filter(x=>x!==name):[...favoriteNames,name];saveFavorites();if(currentPicks.length)renderResults()}
function giftByName(name){return gifts.find(g=>g.name===name)}
async function shareText(text){if(navigator.share)await navigator.share({title:'پیشنهاد کادوپیچ',text});else{await navigator.clipboard.writeText(text);alert('متن پیشنهاد کپی شد.')}}
function shareGift(name){const g=giftByName(name);if(g)shareText(`${g.name}\n${g.desc}\n${buyUrl(g)}`).catch(()=>{})}
function renderFavorites(){const items=favoriteNames.map(giftByName).filter(Boolean);$('favoritesList').innerHTML=items.length?items.map(g=>`<article class="saved-item"><h3>${g.emoji} ${g.name}</h3><div class="source">${g.provider}</div><div class="saved-actions"><a href="${buyUrl(g)}" target="_blank" rel="noopener">مشاهده خرید</a><button data-share-fav="${g.name}">اشتراک</button><button data-remove-fav="${g.name}">حذف</button></div></article>`).join(''):'<div class="drawer-empty">هنوز هدیه‌ای ذخیره نکردی؛ روی «♡ ذخیره» کنار پیشنهادها بزن.</div>';$('favoritesList').querySelectorAll('[data-share-fav]').forEach(b=>b.onclick=()=>shareGift(b.dataset.shareFav));$('favoritesList').querySelectorAll('[data-remove-fav]').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.removeFav))}
function openDrawer(id){$('favoritesDrawer').classList.add('hidden');$('remindersDrawer').classList.add('hidden');$(id).classList.remove('hidden');$('drawerBackdrop').classList.remove('hidden')}
function closeDrawers(){$('favoritesDrawer').classList.add('hidden');$('remindersDrawer').classList.add('hidden');$('drawerBackdrop').classList.add('hidden')}
function calendarUrl(r){const start=r.date.replaceAll('-','')+'T100000';const end=r.date.replaceAll('-','')+'T103000';const body=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${start}\nDTEND:${end}\nSUMMARY:${r.name} - وقت پیدا کردن هدیه\nDESCRIPTION:یادآور کادوپیچ\nEND:VEVENT\nEND:VCALENDAR`;return URL.createObjectURL(new Blob([body],{type:'text/calendar;charset=utf-8'}))}
function renderReminders(){reminders.sort((a,b)=>a.date.localeCompare(b.date));$('remindersList').innerHTML=reminders.length?reminders.map(r=>`<article class="reminder-item"><div><h3>${r.name}</h3><p>${r.date}</p></div><div class="saved-actions"><a data-calendar="${r.id}" download="kadopych-reminder.ics">افزودن به تقویم</a><button data-remove-reminder="${r.id}">حذف</button></div></article>`).join(''):'<div class="drawer-empty">هنوز یادآوری ثبت نشده است.</div>';$('remindersList').querySelectorAll('[data-calendar]').forEach(a=>{const r=reminders.find(x=>x.id===a.dataset.calendar);a.href=calendarUrl(r)});$('remindersList').querySelectorAll('[data-remove-reminder]').forEach(b=>b.onclick=()=>{reminders=reminders.filter(x=>x.id!==b.dataset.removeReminder);localStorage.setItem('kadopych:reminders',JSON.stringify(reminders));renderReminders()})}
function checkReminders(){const today=new Date().toISOString().slice(0,10);let changed=false;reminders.forEach(r=>{if(r.date<=today&&!r.notified&&'Notification'in window&&Notification.permission==='granted'){new Notification('وقت کادوپیچه! 🎁',{body:`برای ${r.name} یک هدیه‌ی خوب پیدا کن.`});r.notified=true;changed=true}});if(changed)localStorage.setItem('kadopych:reminders',JSON.stringify(reminders))}
$('startBtn').onclick=restart;$('restartBtn').onclick=restart;$('restartTop').onclick=restart;$('backBtn').onclick=()=>{if(step){step--;renderQuestion()}else show('intro')};$('favoritesBtn').onclick=()=>openDrawer('favoritesDrawer');$('remindersBtn').onclick=()=>openDrawer('remindersDrawer');$('drawerBackdrop').onclick=closeDrawers;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeDrawers);$('shareAllBtn').onclick=()=>currentPicks.length&&shareText('پیشنهادهای کادوپیچ:\n'+currentPicks.map((g,i)=>`${i+1}. ${g.name}`).join('\n')).catch(()=>{});$('reminderDate').min=new Date().toISOString().slice(0,10);$('reminderForm').onsubmit=async e=>{e.preventDefault();const name=$('reminderName').value.trim(),date=$('reminderDate').value;if(!name||!date)return;if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();reminders.push({id:String(Date.now()),name,date,notified:false});localStorage.setItem('kadopych:reminders',JSON.stringify(reminders));e.target.reset();renderReminders()};renderQuestion();saveFavorites();renderReminders();checkReminders();setInterval(checkReminders,60000);

if(document.modelContext?.registerTool){
 const allowed=Object.fromEntries(questions.map(q=>[q.key,new Set(q.options.map(o=>o[0]))]));
 document.modelContext.registerTool({name:'complete_gift_recommendation',title:'دریافت پیشنهاد هدیه',description:'پاسخ‌های کاربر را ثبت می‌کند و ۱۲ پیشنهاد متناسب را در صفحه نمایش می‌دهد.',inputSchema:{type:'object',properties:Object.fromEntries(questions.map(q=>[q.key,{type:'string',enum:q.options.map(o=>o[0])}])),required:questions.map(q=>q.key),additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){for(const q of questions){if(!allowed[q.key].has(input?.[q.key]))throw new Error(`پاسخ نامعتبر برای ${q.key}`);const opt=q.options.find(o=>o[0]===input[q.key]);answers[q.key]={value:opt[0],label:opt[1]}}renderResults();return{status:'completed',suggestions:[...document.querySelectorAll('.gift-card h3')].map(el=>el.textContent)}}});
}
